{% extends "base.html" %}

{% block content %}
<h1>📊 Výsledky spracovania</h1>

{% if players %}
    <table>
        <thead>
            <tr>
                <th>🎖️ Nick</th>
                <th>📊 WN8</th>
                <th>📅 Posledná aktivita</th>
                <th>🌍 Krajina</th>
            </tr>
        </thead>
        <tbody>
            {% for player in players %}
                <tr>
                    <td>{{ player.nickname }}</td>
                    <td>{{ player.wn8 }}</td>
                    <td>{{ player.last_battle_time }}</td>
                    <td>{{ player.nation or 'Nezistené' }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>⚠️ Žiadni hráči neboli nájdení podľa aktuálneho filtra.</p>
{% endif %}

<a href="/" class="button">🔙 Späť na úvod</a>
{% endblock %}
